# Generated by Django 3.1.13 on 2021-09-13 11:02

import api_img.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип изображения')),
                ('big_image', models.ImageField(upload_to='images/api_img/big/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Файл должен быть одним из: jpg, jpeg'), api_img.models.validate_file_image_max_size], verbose_name='Большое изображение')),
                ('min_image', models.ImageField(blank=True, null=True, upload_to='images/api_img/min/', verbose_name='Маленькое изображение')),
            ],
        ),
    ]
