# Generated by Django 3.1.13 on 2021-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/api_img/big/', verbose_name='Большое изображение'),
        ),
        migrations.AlterField(
            model_name='images',
            name='type',
            field=models.CharField(choices=[('photo', 'photo'), ('filter', 'filter'), ('result', 'result')], default='photo', max_length=6, verbose_name='Тип изображения'),
        ),
    ]
