# Generated by Django 3.1.13 on 2021-09-16 10:03

import api_img.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_img', '0002_auto_20210916_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/api_img/big/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'], message='Файл должен быть одним из: jpg, jpeg'), api_img.models.validate_file_image_max_size], verbose_name='Большое изображение'),
        ),
    ]
