# Generated by Django 3.2.6 on 2021-08-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='Изображения/%Y/%m/%d/'),
        ),
    ]
