# Generated by Django 3.2.6 on 2021-08-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_auto_20210825_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
