# Generated by Django 3.2.6 on 2021-08-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_auto_20210825_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='cat',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
