# Generated by Django 3.2.7 on 2021-09-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/img/', verbose_name='Маленькое изображение')),
            ],
        ),
    ]
