# Generated by Django 3.2.6 on 2021-08-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python_section',
            name='photo',
            field=models.ImageField(default=False, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
