# Generated by Django 3.1.5 on 2021-09-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0004_auto_20210824_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='python_lesson',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='python_section',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
