# Generated by Django 3.2.6 on 2021-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, upload_to='photos/store/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
        ),
    ]
