# Generated by Django 3.2.6 on 2021-09-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
