# Generated by Django 3.2.6 on 2021-09-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
