# Generated by Django 3.1.5 on 2021-09-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210905_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='big_photo',
            field=models.ImageField(blank=True, upload_to='photos/store/big/', verbose_name='Большое Фото'),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_photo',
            field=models.ImageField(default='', upload_to='photos/store/small/', verbose_name='Маленькое Фото'),
        ),
    ]
