# Generated by Django 3.1.5 on 2021-09-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210906_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='big_photo',
            field=models.ImageField(upload_to='photos/store/big/', verbose_name='Большое Фото'),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_photo',
            field=models.ImageField(default=' ', upload_to='photos/store/small/', verbose_name='Маленькое Фото'),
        ),
    ]
