# Generated by Django 3.1.5 on 2021-09-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210906_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
